name: Config Import
description: Clever configuration import.
package: Configuration
type: module
core: 8.x
core_version_requirement: ^8 || ^9

test_dependencies:
  - features (>=8.x-3.x-dev)

# Information added by Drupal.org packaging script on 2020-10-20
version: '8.x-2.0-rc1'
project: 'confi'
datestamp: 1603195397
